In [1]:
import pandas as pd
import numpy as np
df=pd.read_csv(r"C:\data analytics task 1\dirty_cafe_sales.csv")
df.isnull().sum()
df.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [2]:
df.replace(['ERROR','UNKNOWN'],np.nan,inplace=True)
df.isnull().sum()

Transaction ID         0
Item                 969
Quantity             479
Price Per Unit       533
Total Spent          502
Payment Method      3178
Location            3961
Transaction Date     460
dtype: int64

In [3]:
df['Quantity']=pd.to_numeric(df['Quantity'],errors='coerce')
df['Price Per Unit']=pd.to_numeric(df['Price Per Unit'],errors='coerce')
df['Total Spent']=pd.to_numeric(df['Total Spent'],errors='coerce')
df['Transaction Date']=pd.to_datetime(df['Transaction Date'],errors='coerce')

In [4]:
df.isnull().sum()

Transaction ID         0
Item                 969
Quantity             479
Price Per Unit       533
Total Spent          502
Payment Method      3178
Location            3961
Transaction Date     460
dtype: int64

In [5]:
df.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4.0,1.0,NaN,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2.0,5.0,10.0,NaN,NaN,2023-04-27
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [6]:
df['Item'].fillna(df['Item'].mode()[0], inplace=True)

C:\Users\girid\AppData\Local\Temp\ipykernel_5752\303095028.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Item'].fillna(df['Item'].mode()[0], inplace=True)

0         Coffee
1           Cake
2         Cookie
3          Salad
4         Coffee
          ...
9995      Coffee
9996       Juice
9997      Coffee
9998      Cookie
9999    Sandwich
Name: Item, Length: 10000, dtype: str

In [7]:
df['Quantity'].fillna(df['Quantity'].median(),inplace=True)

C:\Users\girid\AppData\Local\Temp\ipykernel_5752\549334851.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Quantity'].fillna(df['Quantity'].median(),inplace=True)

0       2.0
1       4.0
2       4.0
3       2.0
4       2.0
       ...
9995    2.0
9996    3.0
9997    4.0
9998    3.0
9999    3.0
Name: Quantity, Length: 10000, dtype: float64

In [8]:
df.isnull().sum()

Transaction ID         0
Item                 969
Quantity             479
Price Per Unit       533
Total Spent          502
Payment Method      3178
Location            3961
Transaction Date     460
dtype: int64

In [9]:
df['Price Per Unit'].fillna(df['Price Per Unit'].mean(),inplace=True)

C:\Users\girid\AppData\Local\Temp\ipykernel_5752\3702569498.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Price Per Unit'].fillna(df['Price Per Unit'].mean(),inplace=True)

0       2.000000
1       3.000000
2       1.000000
3       5.000000
4       2.000000
          ...
9995    2.000000
9996    2.949984
9997    2.000000
9998    2.949984
9999    4.000000
Name: Price Per Unit, Length: 10000, dtype: float64

In [10]:
df['Total Spent'].fillna(df['Total Spent'].mean(),inplace=True)

C:\Users\girid\AppData\Local\Temp\ipykernel_5752\1098853838.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Total Spent'].fillna(df['Total Spent'].mean(),inplace=True)

0        4.000000
1       12.000000
2        8.924352
3       10.000000
4        4.000000
          ...
9995     4.000000
9996     3.000000
9997     8.000000
9998     3.000000
9999    12.000000
Name: Total Spent, Length: 10000, dtype: float64

In [11]:
df['Payment Method'].fillna('Unknown',inplace=True)
df['Location'].fillna('Unknown',inplace=True)
df['Transaction Date'].fillna(df['Transaction Date'].mode()[0],inplace=True)

C:\Users\girid\AppData\Local\Temp\ipykernel_5752\1768900818.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Payment Method'].fillna('Unknown',inplace=True)
C:\Users\girid\AppData\Local\Temp\ipykernel_5752\1768900818.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Location'].fillna('Unknown',inplace=True)
C:\Users\girid\AppData\Local\Temp\ipykernel_5752\1768900818.py:3: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Transaction Date'].fillna(df['Transaction Date'].mode()[0],inplace=True)

0      2023-09-08
1      2023-05-16
2      2023-07-19
3      2023-04-27
4      2023-06-11
          ...
9995   2023-08-30
9996   2023-06-02
9997   2023-03-02
9998   2023-12-02
9999   2023-11-07
Name: Transaction Date, Length: 10000, dtype: datetime64[us]

In [12]:
df['Total Spent']=df['Quantity']*df['Price Per Unit']

In [13]:
df['Calculated Total']=df['Quantity']*df['Price Per Unit']

In [14]:
df['Day'] = df['Transaction Date'].dt.day_name()

In [15]:
df.isnull().sum()

Transaction ID         0
Item                 969
Quantity             479
Price Per Unit       533
Total Spent          994
Payment Method      3178
Location            3961
Transaction Date     460
Calculated Total     994
Day                  460
dtype: int64

In [16]:
df.head(20)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date,Calculated Total,Day
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08,4.0,Friday
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16,12.0,Tuesday
2,TXN_4271903,Cookie,4.0,1.0,4.0,Credit Card,In-store,2023-07-19,4.0,Wednesday
3,TXN_7034554,Salad,2.0,5.0,10.0,NaN,NaN,2023-04-27,10.0,Thursday
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11,4.0,Sunday
5,TXN_2602893,Smoothie,5.0,4.0,20.0,Credit Card,NaN,2023-03-31,20.0,Friday
6,TXN_4433211,NaN,3.0,3.0,9.0,NaN,Takeaway,2023-10-06,9.0,Friday
7,TXN_6699534,Sandwich,4.0,4.0,16.0,Cash,NaN,2023-10-28,16.0,Saturday
8,TXN_4717867,NaN,5.0,3.0,15.0,NaN,Takeaway,2023-07-28,15.0,Friday
9,TXN_2064365,Sandwich,5.0,4.0,20.0,NaN,In-store,2023-12-31,20.0,Sunday
10,TXN_2548360,Salad,5.0,5.0,25.0,Cash,Takeaway,2023-11-07,25.0,Tuesday
11,TXN_3051279,Sandwich,2.0,4.0,8.0,Credit Card,Takeaway,NaT,8.0,NaN
12,TXN_7619095,Sandwich,2.0,4.0,8.0,Cash,In-store,2023-05-03,8.0,Wednesday
13,TXN_9437049,Cookie,5.0,1.0,5.0,NaN,Takeaway,2023-06-01,5.0,Thursday
14,TXN_8915701,NaN,2.0,1.5,3.0,NaN,In-store,2023-03-21,3.0,Tuesday
15,TXN_2847255,Salad,3.0,5.0,15.0,Credit Card,In-store,2023-11-15,15.0,Wednesday
16,TXN_3765707,Sandwich,1.0,4.0,4.0,NaN,NaN,2023-06-10,4.0,Saturday
17,TXN_6769710,Juice,2.0,3.0,6.0,Cash,In-store,2023-02-24,6.0,Friday
18,TXN_8876618,Cake,5.0,3.0,15.0,Cash,NaN,2023-03-25,15.0,Saturday
19,TXN_3709394,Juice,4.0,3.0,12.0,Cash,Takeaway,2023-01-15,12.0,Sunday

In [17]:
df.to_csv("cleaned_data.csv", index=False)

In [21]:
df.info()
df.isnull().sum()
df.head()
df.describe()
df.duplicated().sum()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  str
 1   Item              9031 non-null   str
 2   Quantity          9521 non-null   float64
 3   Price Per Unit    9467 non-null   float64
 4   Total Spent       9006 non-null   float64
 5   Payment Method    6822 non-null   str
 6   Location          6039 non-null   str
 7   Transaction Date  9540 non-null   datetime64[us]
 8   Calculated Total  9006 non-null   float64
 9   Day               9540 non-null   str
dtypes: datetime64[us](1), float64(4), str(5)
memory usage: 781.4 KB

np.int64(0)

In [18]:
df.describe()

,Quantity,Price Per Unit,Total Spent,Transaction Date,Calculated Total
count,9521.000000,9467.000000,9006.000000,9540,9006.000000
mean,3.028463,2.949984,8.936098,2023-07-01 23:00:31.698113,8.936098
min,1.000000,1.000000,1.000000,2023-01-01 00:00:00,1.000000
25%,2.000000,2.000000,4.000000,2023-04-01 00:00:00,4.000000
50%,3.000000,3.000000,8.000000,2023-07-02 00:00:00,8.000000
75%,4.000000,4.000000,12.000000,2023-10-02 00:00:00,12.000000
max,5.000000,5.000000,25.000000,2023-12-31 00:00:00,25.000000
std,1.419007,1.278450,5.994375,NaN,5.994375